export const UPDATE_ROVER_DIRECTION = 'UPDATE_ROVER_DIRECTION';
export const UPDATE_ROVER_POSITION = 'UPDATE_ROVER_POSITION';
export const UPDATE_COMMANDS = 'UPDATE_COMMANDS';
export const RESET = 'RESET';
